name: "mqttx"
description: "MQTT Web Client"
version: "1.0.7"
ingress: true
ingress_port: 6789
slug: "mqttx"
init: false
host_network: true
ports:
  6789/tcp: 6789
ports_description:
  6789/tcp: Web interface
# webui: http://[HOST]:[PORT:6789]/index.html
arch:
  - armv7
options:
  host: "192.168.0.1"
  username: ""
  password: ""
schema:
  host: str
  username: str
  password: str
