name: "Solix 2 MQTT"
description: "Anker Solix E1600 MQTT integration"
version: "1.3.3"
slug: "solix2mqtt"
init: false
host_network: true
map:
  - addons:rw
homeassistant_api: true
arch:
  - armv7
  - i386
options:
  user: ""
  password: ""
  site_name: "Balkonsolar"
  country: "DE"
  mqtt_uri: "mqtt://homeassistant.local:1883"
  mqtt_username: ""
  mqtt_password: ""
  mqtt_topic: "anker/solix"
  poll_interval: 30
schema:
  user: str
  password: str
  site_name: str
  country: str
  mqtt_uri: str
  mqtt_username: str
  mqtt_password: str
  mqtt_topic: str
  poll_interval: int
