name: "Solix 2 MQTT"
description: "Anker Solix E1600 MQTT integration"
version: "1.0.8"
slug: "solix2mqtt"
init: false
host_network: true
map:
  - addons:rw
homeassistant_api: true
arch:
  - armv7
  - i386
options:
  user: "markus.mauch@gmail.com"
  password: "C@qF3ab$u&RYNhgsJJ"
  country: "DE"
  mqtt_uri: "mqtt://192.168.0.4:1883"
  mqtt_username: "pi"
  mqtt_password: ""
schema:
  user: str
  password: str
  country: str
  mqtt_uri: str
  mqtt_username: str
  mqtt_password: str
