name: "Solix 2 MQTT"
description: "Anker Solix E1600 MQTT integration"
version: "1.1.1"
slug: "solix2mqtt"
init: false
host_network: true
map:
  - addons:rw
homeassistant_api: true
arch:
  - armv7
  - i386
options:
  user: ""
  password: ""
  country: ""
  mqtt_host: ""
  mqtt_username: ""
  mqtt_password: ""
  poll_interval: 30
schema:
  user: str
  password: str
  country: str
  mqtt_host: str
  mqtt_username: str
  mqtt_password: str
  poll_interval: int
