name: "keyble-mqtt"
description: "Eqiva Smart Lock Bluetooth MQTT"
version: "1.0.7"
slug: "keyble-mqtt"
init: false
host_network: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
arch:
  - armv7
options:
  address: ""
  user_id: 0
  user_key: ""
  username: ""
  password: ""
schema:
  address: str
  user_id: int
  user_key: str
  username: str
  password: str